# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://sethbroberts.github.io/funmeas/"

git_url = "https://github.com/sethbroberts/funmeas/tree/master/"

def custom_doc_links(name): return None
