# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['make_cartesian_product']

# Cell
from typing import Iterable, Any, List
from itertools import product

def make_cartesian_product(S1: Iterable[Any], S2: Iterable[Any]) -> List:
    return list(product(S1, S2))